=begin
#Service Invoice API (api.nfe.io)

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for NfeClient::CompaniesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CompaniesApi' do
  before do
    # run before each test
    @instance = NfeClient::CompaniesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompaniesApi' do
    it 'should create an instact of CompaniesApi' do
      expect(@instance).to be_instance_of(NfeClient::CompaniesApi)
    end
  end

  # unit tests for create_company
  # Criar uma empresa
  # 
  # @param item Dados da empresa
  # @param [Hash] opts the optional parameters
  # @return [CompanySingleResource]
  describe 'create_company test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_company
  # Excluir uma empresa
  # 
  # @param company_id ID da empresa
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_company test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_companies
  # Listar as empresas ativas de uma conta
  # 
  # @param [Hash] opts the optional parameters
  # @return [CompanyCollectionResource]
  describe 'get_companies test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_company
  # Obter os detalhes de uma empresa
  # 
  # @param company_id_or_tax_number ID da empresa ou Inscrição Federal (CNPJ)
  # @param [Hash] opts the optional parameters
  # @return [CompanySingleResource]
  describe 'get_company test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_company
  # Atualizar uma empresa
  # 
  # @param company_id ID da empresa
  # @param item Dados da empresa
  # @param [Hash] opts the optional parameters
  # @return [CompanySingleResource]
  describe 'update_company test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_company_certificate
  # Upload do certificado digital da empresa usando o codificação multipart/form-data.
  # 
  # @param company_id ID da empresa
  # @param file Arquivo do certificado digital com extensao PFX ou P12
  # @param password Senha do arquivo do certificado digital
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'upload_company_certificate test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
