=begin
#Service Invoice API (api.nfe.io)

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for NfeClient::LegalPeopleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LegalPeopleApi' do
  before do
    # run before each test
    @instance = NfeClient::LegalPeopleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LegalPeopleApi' do
    it 'should create an instact of LegalPeopleApi' do
      expect(@instance).to be_instance_of(NfeClient::LegalPeopleApi)
    end
  end

  # unit tests for get_legal_people
  # Listar as pessoas jurídicas ativas
  # 
  # @param company_id ID da empresa
  # @param [Hash] opts the optional parameters
  # @return [LegalPersonSingleResource]
  describe 'get_legal_people test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_legal_person
  # Obter os detalhes de uma pessoa jurídica
  # 
  # @param company_id ID da empresa
  # @param id ID da pessoa juridica
  # @param [Hash] opts the optional parameters
  # @return [LegalPersonSingleResource]
  describe 'get_legal_person test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
