=begin
#Service Invoice API (api.nfe.io)

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for NfeClient::NaturalPeopleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NaturalPeopleApi' do
  before do
    # run before each test
    @instance = NfeClient::NaturalPeopleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NaturalPeopleApi' do
    it 'should create an instact of NaturalPeopleApi' do
      expect(@instance).to be_instance_of(NfeClient::NaturalPeopleApi)
    end
  end

  # unit tests for get_natural_people
  # Listar as pessoas físicas ativas
  # 
  # @param company_id ID da empresa
  # @param [Hash] opts the optional parameters
  # @return [NaturalPersonCollectionResource]
  describe 'get_natural_people test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_natural_person
  # Obter os detalhes de uma pessoa física
  # 
  # @param company_id ID da empresa
  # @param id ID da pessoa física
  # @param [Hash] opts the optional parameters
  # @return [NaturalPersonResource]
  describe 'get_natural_person test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
