=begin
#Service Invoice API (api.nfe.io)

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for NfeClient::ServiceInvoicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServiceInvoicesApi' do
  before do
    # run before each test
    @instance = NfeClient::ServiceInvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceInvoicesApi' do
    it 'should create an instact of ServiceInvoicesApi' do
      expect(@instance).to be_instance_of(NfeClient::ServiceInvoicesApi)
    end
  end

  # unit tests for cancel_service_invoice
  # Cancelar uma Nota Fiscal de Serviços (NFSE)
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param id ID da Nota Fiscal de Serviço (NFSE)
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'cancel_service_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_service_invoice
  # Emitir uma Nota Fiscal de Serviço (NFSE)
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param item Dados da nota fiscal de serviço
  # @param [Hash] opts the optional parameters
  # @return [ServiceInvoiceResource]
  describe 'create_service_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pdf_version_of_service_invoice
  # Download do PDF da Nota Fiscal de Serviço (NFSE)
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param id ID da Nota Fiscal de Serviço (NFSE)
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_pdf_version_of_service_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_service_invoice
  # Obter os detalhes de uma Nota Fiscal de Serviço (NFSE)
  # Você precisará do API Key da Empresa
  # @param company_id ID da empresa
  # @param id ID da Nota Fiscal de Serviço (NFSE)
  # @param [Hash] opts the optional parameters
  # @return [ServiceInvoiceResource]
  describe 'get_service_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_service_invoices
  # Listar as Notas Fiscais de Serviço (NFSE)
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_count Items por página
  # @option opts [Integer] :page_index Número da página
  # @return [ServiceInvoiceCollectionResource]
  describe 'get_service_invoices test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_xml_version_of_service_invoice
  # Download do XML da Nota Fiscal de Serviço (NFSE)
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param id ID da Nota Fiscal de Serviço (NFSE)
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_xml_version_of_service_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pull_all_service_invoices_from_prefeitura
  # Consulta Notas Fiscais de Serviço (NFSE) da Prefeitura
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param date_range 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'pull_all_service_invoices_from_prefeitura test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send_service_invoice_by_email
  # Enviar email para o Tomador com a Nota Fiscal de Serviço (NFSE)
  # Você precisará do APIKEY da Empresa
  # @param company_id ID da empresa
  # @param id ID da Nota Fiscal de Serviço (NFSE)
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'send_service_invoice_by_email test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
