=begin
#Service Invoice API (api.nfe.io)

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module NfeClient

  class CompanyResource
    # Identificação
    attr_accessor :id

    # Nome ou Razão Social
    attr_accessor :name

    # Nome fantasia
    attr_accessor :trade_name

    # CNPJ ou CPF
    attr_accessor :federal_tax_number

    # Email
    attr_accessor :email

    # Endereço
    attr_accessor :address

    # Data abertura da empresa
    attr_accessor :openning_date

    # Tipo do Regime Tributário
    attr_accessor :tax_regime

    # Tipo do regime especial de tributação
    attr_accessor :special_tax_regime

    # Código da Natureza Jurídica
    attr_accessor :legal_nature

    # Atividades da Empresa
    attr_accessor :economic_activities

    # Número de Inscricação na Junta Comercial
    attr_accessor :company_registry_number

    # Número de Inscricação na SEFAZ (IE)
    attr_accessor :regional_tax_number

    # Número de Inscricação na Prefeitura (CCM)
    attr_accessor :municipal_tax_number

    # RPS número serie
    attr_accessor :rps_serial_number

    # RPS número
    attr_accessor :rps_number

    # Ambiente de processamento
    attr_accessor :environment

    # Status no sistema
    attr_accessor :fiscal_status

    # Certificado
    attr_accessor :certificate

    # Data de criação
    attr_accessor :created_on

    # Data da última modificação
    attr_accessor :modified_on

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'trade_name' => :'tradeName',
        :'federal_tax_number' => :'federalTaxNumber',
        :'email' => :'email',
        :'address' => :'address',
        :'openning_date' => :'openningDate',
        :'tax_regime' => :'taxRegime',
        :'special_tax_regime' => :'specialTaxRegime',
        :'legal_nature' => :'legalNature',
        :'economic_activities' => :'economicActivities',
        :'company_registry_number' => :'companyRegistryNumber',
        :'regional_tax_number' => :'regionalTaxNumber',
        :'municipal_tax_number' => :'municipalTaxNumber',
        :'rps_serial_number' => :'rpsSerialNumber',
        :'rps_number' => :'rpsNumber',
        :'environment' => :'environment',
        :'fiscal_status' => :'fiscalStatus',
        :'certificate' => :'certificate',
        :'created_on' => :'createdOn',
        :'modified_on' => :'modifiedOn'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'trade_name' => :'String',
        :'federal_tax_number' => :'Integer',
        :'email' => :'String',
        :'address' => :'Address',
        :'openning_date' => :'DateTime',
        :'tax_regime' => :'String',
        :'special_tax_regime' => :'String',
        :'legal_nature' => :'String',
        :'economic_activities' => :'Array<EconomicActivity>',
        :'company_registry_number' => :'Integer',
        :'regional_tax_number' => :'Integer',
        :'municipal_tax_number' => :'String',
        :'rps_serial_number' => :'String',
        :'rps_number' => :'Integer',
        :'environment' => :'String',
        :'fiscal_status' => :'String',
        :'certificate' => :'CompanyCertificate',
        :'created_on' => :'DateTime',
        :'modified_on' => :'DateTime'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'tradeName')
        self.trade_name = attributes[:'tradeName']
      end

      if attributes.has_key?(:'federalTaxNumber')
        self.federal_tax_number = attributes[:'federalTaxNumber']
      end

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.has_key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.has_key?(:'openningDate')
        self.openning_date = attributes[:'openningDate']
      end

      if attributes.has_key?(:'taxRegime')
        self.tax_regime = attributes[:'taxRegime']
      end

      if attributes.has_key?(:'specialTaxRegime')
        self.special_tax_regime = attributes[:'specialTaxRegime']
      end

      if attributes.has_key?(:'legalNature')
        self.legal_nature = attributes[:'legalNature']
      end

      if attributes.has_key?(:'economicActivities')
        if (value = attributes[:'economicActivities']).is_a?(Array)
          self.economic_activities = value
        end
      end

      if attributes.has_key?(:'companyRegistryNumber')
        self.company_registry_number = attributes[:'companyRegistryNumber']
      end

      if attributes.has_key?(:'regionalTaxNumber')
        self.regional_tax_number = attributes[:'regionalTaxNumber']
      end

      if attributes.has_key?(:'municipalTaxNumber')
        self.municipal_tax_number = attributes[:'municipalTaxNumber']
      end

      if attributes.has_key?(:'rpsSerialNumber')
        self.rps_serial_number = attributes[:'rpsSerialNumber']
      end

      if attributes.has_key?(:'rpsNumber')
        self.rps_number = attributes[:'rpsNumber']
      end

      if attributes.has_key?(:'environment')
        self.environment = attributes[:'environment']
      end

      if attributes.has_key?(:'fiscalStatus')
        self.fiscal_status = attributes[:'fiscalStatus']
      end

      if attributes.has_key?(:'certificate')
        self.certificate = attributes[:'certificate']
      end

      if attributes.has_key?(:'createdOn')
        self.created_on = attributes[:'createdOn']
      end

      if attributes.has_key?(:'modifiedOn')
        self.modified_on = attributes[:'modifiedOn']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @federal_tax_number.nil?
      return false if @email.nil?
      return false if @address.nil?
      return false if @openning_date.nil?
      return false if @tax_regime.nil?
      special_tax_regime_validator = EnumAttributeValidator.new('String', ["Nenhum", "MicroempresaMunicipal", "Estimativa", "SociedadeDeProfissionais", "Cooperativa", "MicroempreendedorIndividual", "MicroempresarioEmpresaPequenoPorte", "Automatico"])
      return false unless special_tax_regime_validator.valid?(@special_tax_regime)
      return false if @legal_nature.nil?
      legal_nature_validator = EnumAttributeValidator.new('String', ["EmpresaPublica", "SociedadeEconomiaMista", "SociedadeAnonimaAberta", "SociedadeAnonimaFechada", "SociedadeEmpresariaLimitada", "SociedadeEmpresariaEmNomeColetivo", "SociedadeEmpresariaEmComanditaSimples", "SociedadeEmpresariaEmComanditaporAcoes", "SociedadeemContaParticipacao", "Empresario", "Cooperativa", "ConsorcioSociedades", "GrupoSociedades", "EmpresaDomiciliadaExterior", "ClubeFundoInvestimento", "SociedadeSimplesPura", "SociedadeSimplesLimitada", "SociedadeSimplesEmNomeColetivo", "SociedadeSimplesEmComanditaSimples", "EmpresaBinacional", "ConsorcioEmpregadores", "ConsorcioSimples", "EireliNaturezaEmpresaria", "EireliNaturezaSimples", "ServicoNotarial", "FundacaoPrivada", "ServicoSocialAutonomo", "CondominioEdilicio", "ComissaoConciliacaoPrevia", "EntidadeMediacaoArbitragem", "PartidoPolitico", "EntidadeSindical", "EstabelecimentoBrasilFundacaoAssociacaoEstrangeiras", "FundacaoAssociacaoDomiciliadaExterior", "OrganizacaoReligiosa", "ComunidadeIndigena", "FundoPrivado", "AssociacaoPrivada"])
      return false unless legal_nature_validator.valid?(@legal_nature)
      return false if @municipal_tax_number.nil?
      environment_validator = EnumAttributeValidator.new('String', ["Development", "Production", "Staging"])
      return false unless environment_validator.valid?(@environment)
      fiscal_status_validator = EnumAttributeValidator.new('String', ["None", "Active", "CityNotSupported", "Pending", "Inactive"])
      return false unless fiscal_status_validator.valid?(@fiscal_status)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] special_tax_regime Object to be assigned
    def special_tax_regime=(special_tax_regime)
      validator = EnumAttributeValidator.new('String', ["Nenhum", "MicroempresaMunicipal", "Estimativa", "SociedadeDeProfissionais", "Cooperativa", "MicroempreendedorIndividual", "MicroempresarioEmpresaPequenoPorte", "Automatico"])
      unless validator.valid?(special_tax_regime)
        fail ArgumentError, "invalid value for 'special_tax_regime', must be one of #{validator.allowable_values}."
      end
      @special_tax_regime = special_tax_regime
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] legal_nature Object to be assigned
    def legal_nature=(legal_nature)
      validator = EnumAttributeValidator.new('String', ["EmpresaPublica", "SociedadeEconomiaMista", "SociedadeAnonimaAberta", "SociedadeAnonimaFechada", "SociedadeEmpresariaLimitada", "SociedadeEmpresariaEmNomeColetivo", "SociedadeEmpresariaEmComanditaSimples", "SociedadeEmpresariaEmComanditaporAcoes", "SociedadeemContaParticipacao", "Empresario", "Cooperativa", "ConsorcioSociedades", "GrupoSociedades", "EmpresaDomiciliadaExterior", "ClubeFundoInvestimento", "SociedadeSimplesPura", "SociedadeSimplesLimitada", "SociedadeSimplesEmNomeColetivo", "SociedadeSimplesEmComanditaSimples", "EmpresaBinacional", "ConsorcioEmpregadores", "ConsorcioSimples", "EireliNaturezaEmpresaria", "EireliNaturezaSimples", "ServicoNotarial", "FundacaoPrivada", "ServicoSocialAutonomo", "CondominioEdilicio", "ComissaoConciliacaoPrevia", "EntidadeMediacaoArbitragem", "PartidoPolitico", "EntidadeSindical", "EstabelecimentoBrasilFundacaoAssociacaoEstrangeiras", "FundacaoAssociacaoDomiciliadaExterior", "OrganizacaoReligiosa", "ComunidadeIndigena", "FundoPrivado", "AssociacaoPrivada"])
      unless validator.valid?(legal_nature)
        fail ArgumentError, "invalid value for 'legal_nature', must be one of #{validator.allowable_values}."
      end
      @legal_nature = legal_nature
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] environment Object to be assigned
    def environment=(environment)
      validator = EnumAttributeValidator.new('String', ["Development", "Production", "Staging"])
      unless validator.valid?(environment)
        fail ArgumentError, "invalid value for 'environment', must be one of #{validator.allowable_values}."
      end
      @environment = environment
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fiscal_status Object to be assigned
    def fiscal_status=(fiscal_status)
      validator = EnumAttributeValidator.new('String', ["None", "Active", "CityNotSupported", "Pending", "Inactive"])
      unless validator.valid?(fiscal_status)
        fail ArgumentError, "invalid value for 'fiscal_status', must be one of #{validator.allowable_values}."
      end
      @fiscal_status = fiscal_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          trade_name == o.trade_name &&
          federal_tax_number == o.federal_tax_number &&
          email == o.email &&
          address == o.address &&
          openning_date == o.openning_date &&
          tax_regime == o.tax_regime &&
          special_tax_regime == o.special_tax_regime &&
          legal_nature == o.legal_nature &&
          economic_activities == o.economic_activities &&
          company_registry_number == o.company_registry_number &&
          regional_tax_number == o.regional_tax_number &&
          municipal_tax_number == o.municipal_tax_number &&
          rps_serial_number == o.rps_serial_number &&
          rps_number == o.rps_number &&
          environment == o.environment &&
          fiscal_status == o.fiscal_status &&
          certificate == o.certificate &&
          created_on == o.created_on &&
          modified_on == o.modified_on
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, name, trade_name, federal_tax_number, email, address, openning_date, tax_regime, special_tax_regime, legal_nature, economic_activities, company_registry_number, regional_tax_number, municipal_tax_number, rps_serial_number, rps_number, environment, fiscal_status, certificate, created_on, modified_on].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = NfeClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
