=begin
#Service Invoice API (api.nfe.io)

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module NfeClient

  class ServiceInvoiceResource
    # Identificação
    attr_accessor :id

    # Ambiente de Processamento
    attr_accessor :environment

    # Status do processamento
    attr_accessor :flow_status

    # Mensagem de processamento
    attr_accessor :flow_message

    # Prestador dos serviços
    attr_accessor :provider

    # Tomador dos serviços
    attr_accessor :borrower

    # Número do lote da RPS
    attr_accessor :batch_number

    # Número do protocolo do lote da RPS
    attr_accessor :batch_check_number

    # Número do NFE
    attr_accessor :number

    # Código de Verificação da NFE
    attr_accessor :check_code

    # Status da NFE
    attr_accessor :status

    # Tipo da RPS
    attr_accessor :rps_type

    # Status da RPS
    attr_accessor :rps_status

    # Tipo da tributação
    attr_accessor :taxation_type

    # Data de emissão
    attr_accessor :issued_on

    # Data de cancelamento
    attr_accessor :cancelled_on

    # Número de serie da RPS
    attr_accessor :rps_serial_number

    # Número da RPS
    attr_accessor :rps_number

    # Código do servico prestado no Municipio
    attr_accessor :city_service_code

    # Código do servico prestado federal
    attr_accessor :federal_service_code

    # Descrição do serviço no municipio
    attr_accessor :description

    # Valor do serviços
    attr_accessor :services_amount

    # Valor de deduções
    attr_accessor :deductions_amount

    # Valor do desconto incondicionado
    attr_accessor :discount_unconditioned_amount

    # Valor do desconto condicionado
    attr_accessor :discount_conditioned_amount

    # Valor da base de calculo de impostos
    attr_accessor :base_tax_amount

    # Aliquota do ISS
    attr_accessor :iss_rate

    # Valor do ISS
    attr_accessor :iss_tax_amount

    # Valor retido do Imposto de Renda (IR)
    attr_accessor :ir_amount_withheld

    # Valor retido do PIS
    attr_accessor :pis_amount_withheld

    # Valor retido do COFINS
    attr_accessor :cofins_amount_withheld

    # Valor retido do CSLL
    attr_accessor :csll_amount_withheld

    # Valor retido do INSS
    attr_accessor :inss_amount_withheld

    # Valor retido do ISS
    attr_accessor :iss_amount_withheld

    # Valor de outras retenções
    attr_accessor :others_amount_withheld

    # Valor das retenções
    attr_accessor :amount_withheld

    # Valor líquido
    attr_accessor :amount_net

    # Tributos aproximados
    attr_accessor :approximate_tax

    # Data de criação
    attr_accessor :created_on

    # Data da última modificação
    attr_accessor :modified_on

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'environment' => :'environment',
        :'flow_status' => :'flowStatus',
        :'flow_message' => :'flowMessage',
        :'provider' => :'provider',
        :'borrower' => :'borrower',
        :'batch_number' => :'batchNumber',
        :'batch_check_number' => :'batchCheckNumber',
        :'number' => :'number',
        :'check_code' => :'checkCode',
        :'status' => :'status',
        :'rps_type' => :'rpsType',
        :'rps_status' => :'rpsStatus',
        :'taxation_type' => :'taxationType',
        :'issued_on' => :'issuedOn',
        :'cancelled_on' => :'cancelledOn',
        :'rps_serial_number' => :'rpsSerialNumber',
        :'rps_number' => :'rpsNumber',
        :'city_service_code' => :'cityServiceCode',
        :'federal_service_code' => :'federalServiceCode',
        :'description' => :'description',
        :'services_amount' => :'servicesAmount',
        :'deductions_amount' => :'deductionsAmount',
        :'discount_unconditioned_amount' => :'discountUnconditionedAmount',
        :'discount_conditioned_amount' => :'discountConditionedAmount',
        :'base_tax_amount' => :'baseTaxAmount',
        :'iss_rate' => :'issRate',
        :'iss_tax_amount' => :'issTaxAmount',
        :'ir_amount_withheld' => :'irAmountWithheld',
        :'pis_amount_withheld' => :'pisAmountWithheld',
        :'cofins_amount_withheld' => :'cofinsAmountWithheld',
        :'csll_amount_withheld' => :'csllAmountWithheld',
        :'inss_amount_withheld' => :'inssAmountWithheld',
        :'iss_amount_withheld' => :'issAmountWithheld',
        :'others_amount_withheld' => :'othersAmountWithheld',
        :'amount_withheld' => :'amountWithheld',
        :'amount_net' => :'amountNet',
        :'approximate_tax' => :'approximateTax',
        :'created_on' => :'createdOn',
        :'modified_on' => :'modifiedOn'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'environment' => :'String',
        :'flow_status' => :'String',
        :'flow_message' => :'String',
        :'provider' => :'LegalPerson',
        :'borrower' => :'Person',
        :'batch_number' => :'Integer',
        :'batch_check_number' => :'String',
        :'number' => :'Integer',
        :'check_code' => :'String',
        :'status' => :'String',
        :'rps_type' => :'String',
        :'rps_status' => :'String',
        :'taxation_type' => :'String',
        :'issued_on' => :'DateTime',
        :'cancelled_on' => :'DateTime',
        :'rps_serial_number' => :'String',
        :'rps_number' => :'Integer',
        :'city_service_code' => :'String',
        :'federal_service_code' => :'String',
        :'description' => :'String',
        :'services_amount' => :'Float',
        :'deductions_amount' => :'Float',
        :'discount_unconditioned_amount' => :'Float',
        :'discount_conditioned_amount' => :'Float',
        :'base_tax_amount' => :'Float',
        :'iss_rate' => :'Float',
        :'iss_tax_amount' => :'Float',
        :'ir_amount_withheld' => :'Float',
        :'pis_amount_withheld' => :'Float',
        :'cofins_amount_withheld' => :'Float',
        :'csll_amount_withheld' => :'Float',
        :'inss_amount_withheld' => :'Float',
        :'iss_amount_withheld' => :'Float',
        :'others_amount_withheld' => :'Float',
        :'amount_withheld' => :'Float',
        :'amount_net' => :'Float',
        :'approximate_tax' => :'ServiceInvoiceApproximateTaxesResource',
        :'created_on' => :'DateTime',
        :'modified_on' => :'DateTime'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'environment')
        self.environment = attributes[:'environment']
      end

      if attributes.has_key?(:'flowStatus')
        self.flow_status = attributes[:'flowStatus']
      end

      if attributes.has_key?(:'flowMessage')
        self.flow_message = attributes[:'flowMessage']
      end

      if attributes.has_key?(:'provider')
        self.provider = attributes[:'provider']
      end

      if attributes.has_key?(:'borrower')
        self.borrower = attributes[:'borrower']
      end

      if attributes.has_key?(:'batchNumber')
        self.batch_number = attributes[:'batchNumber']
      end

      if attributes.has_key?(:'batchCheckNumber')
        self.batch_check_number = attributes[:'batchCheckNumber']
      end

      if attributes.has_key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.has_key?(:'checkCode')
        self.check_code = attributes[:'checkCode']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'rpsType')
        self.rps_type = attributes[:'rpsType']
      end

      if attributes.has_key?(:'rpsStatus')
        self.rps_status = attributes[:'rpsStatus']
      end

      if attributes.has_key?(:'taxationType')
        self.taxation_type = attributes[:'taxationType']
      end

      if attributes.has_key?(:'issuedOn')
        self.issued_on = attributes[:'issuedOn']
      end

      if attributes.has_key?(:'cancelledOn')
        self.cancelled_on = attributes[:'cancelledOn']
      end

      if attributes.has_key?(:'rpsSerialNumber')
        self.rps_serial_number = attributes[:'rpsSerialNumber']
      end

      if attributes.has_key?(:'rpsNumber')
        self.rps_number = attributes[:'rpsNumber']
      end

      if attributes.has_key?(:'cityServiceCode')
        self.city_service_code = attributes[:'cityServiceCode']
      end

      if attributes.has_key?(:'federalServiceCode')
        self.federal_service_code = attributes[:'federalServiceCode']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'servicesAmount')
        self.services_amount = attributes[:'servicesAmount']
      end

      if attributes.has_key?(:'deductionsAmount')
        self.deductions_amount = attributes[:'deductionsAmount']
      end

      if attributes.has_key?(:'discountUnconditionedAmount')
        self.discount_unconditioned_amount = attributes[:'discountUnconditionedAmount']
      end

      if attributes.has_key?(:'discountConditionedAmount')
        self.discount_conditioned_amount = attributes[:'discountConditionedAmount']
      end

      if attributes.has_key?(:'baseTaxAmount')
        self.base_tax_amount = attributes[:'baseTaxAmount']
      end

      if attributes.has_key?(:'issRate')
        self.iss_rate = attributes[:'issRate']
      end

      if attributes.has_key?(:'issTaxAmount')
        self.iss_tax_amount = attributes[:'issTaxAmount']
      end

      if attributes.has_key?(:'irAmountWithheld')
        self.ir_amount_withheld = attributes[:'irAmountWithheld']
      end

      if attributes.has_key?(:'pisAmountWithheld')
        self.pis_amount_withheld = attributes[:'pisAmountWithheld']
      end

      if attributes.has_key?(:'cofinsAmountWithheld')
        self.cofins_amount_withheld = attributes[:'cofinsAmountWithheld']
      end

      if attributes.has_key?(:'csllAmountWithheld')
        self.csll_amount_withheld = attributes[:'csllAmountWithheld']
      end

      if attributes.has_key?(:'inssAmountWithheld')
        self.inss_amount_withheld = attributes[:'inssAmountWithheld']
      end

      if attributes.has_key?(:'issAmountWithheld')
        self.iss_amount_withheld = attributes[:'issAmountWithheld']
      end

      if attributes.has_key?(:'othersAmountWithheld')
        self.others_amount_withheld = attributes[:'othersAmountWithheld']
      end

      if attributes.has_key?(:'amountWithheld')
        self.amount_withheld = attributes[:'amountWithheld']
      end

      if attributes.has_key?(:'amountNet')
        self.amount_net = attributes[:'amountNet']
      end

      if attributes.has_key?(:'approximateTax')
        self.approximate_tax = attributes[:'approximateTax']
      end

      if attributes.has_key?(:'createdOn')
        self.created_on = attributes[:'createdOn']
      end

      if attributes.has_key?(:'modifiedOn')
        self.modified_on = attributes[:'modifiedOn']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @environment.nil?
      environment_validator = EnumAttributeValidator.new('String', ["Development", "Production", "Staging"])
      return false unless environment_validator.valid?(@environment)
      flow_status_validator = EnumAttributeValidator.new('String', ["Issued", "Cancelled", "PullFromCityHall", "WaitingCalculateTaxes", "WaitingDefineRpsNumber", "WaitingSend", "WaitingSendCancel", "WaitingReturn", "WaitingDownload", "CancelFailed", "IssueFailed"])
      return false unless flow_status_validator.valid?(@flow_status)
      status_validator = EnumAttributeValidator.new('String', ["None", "Created", "Issued", "Cancelled", "Error"])
      return false unless status_validator.valid?(@status)
      rps_type_validator = EnumAttributeValidator.new('String', ["Rps", "RpsMista", "Cupom"])
      return false unless rps_type_validator.valid?(@rps_type)
      rps_status_validator = EnumAttributeValidator.new('String', ["Normal", "Canceled", "Lost"])
      return false unless rps_status_validator.valid?(@rps_status)
      taxation_type_validator = EnumAttributeValidator.new('String', ["None", "WithinCity", "OutsideCity", "Export", "Free", "OutsideCityFree", "Immune", "OutsideCityImmune", "SuspendedCourtDecision", "OutsideCitySuspended", "SuspendedAdministrativeProcedure"])
      return false unless taxation_type_validator.valid?(@taxation_type)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] environment Object to be assigned
    def environment=(environment)
      validator = EnumAttributeValidator.new('String', ["Development", "Production", "Staging"])
      unless validator.valid?(environment)
        fail ArgumentError, "invalid value for 'environment', must be one of #{validator.allowable_values}."
      end
      @environment = environment
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] flow_status Object to be assigned
    def flow_status=(flow_status)
      validator = EnumAttributeValidator.new('String', ["Issued", "Cancelled", "PullFromCityHall", "WaitingCalculateTaxes", "WaitingDefineRpsNumber", "WaitingSend", "WaitingSendCancel", "WaitingReturn", "WaitingDownload", "CancelFailed", "IssueFailed"])
      unless validator.valid?(flow_status)
        fail ArgumentError, "invalid value for 'flow_status', must be one of #{validator.allowable_values}."
      end
      @flow_status = flow_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["None", "Created", "Issued", "Cancelled", "Error"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for 'status', must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] rps_type Object to be assigned
    def rps_type=(rps_type)
      validator = EnumAttributeValidator.new('String', ["Rps", "RpsMista", "Cupom"])
      unless validator.valid?(rps_type)
        fail ArgumentError, "invalid value for 'rps_type', must be one of #{validator.allowable_values}."
      end
      @rps_type = rps_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] rps_status Object to be assigned
    def rps_status=(rps_status)
      validator = EnumAttributeValidator.new('String', ["Normal", "Canceled", "Lost"])
      unless validator.valid?(rps_status)
        fail ArgumentError, "invalid value for 'rps_status', must be one of #{validator.allowable_values}."
      end
      @rps_status = rps_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] taxation_type Object to be assigned
    def taxation_type=(taxation_type)
      validator = EnumAttributeValidator.new('String', ["None", "WithinCity", "OutsideCity", "Export", "Free", "OutsideCityFree", "Immune", "OutsideCityImmune", "SuspendedCourtDecision", "OutsideCitySuspended", "SuspendedAdministrativeProcedure"])
      unless validator.valid?(taxation_type)
        fail ArgumentError, "invalid value for 'taxation_type', must be one of #{validator.allowable_values}."
      end
      @taxation_type = taxation_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          environment == o.environment &&
          flow_status == o.flow_status &&
          flow_message == o.flow_message &&
          provider == o.provider &&
          borrower == o.borrower &&
          batch_number == o.batch_number &&
          batch_check_number == o.batch_check_number &&
          number == o.number &&
          check_code == o.check_code &&
          status == o.status &&
          rps_type == o.rps_type &&
          rps_status == o.rps_status &&
          taxation_type == o.taxation_type &&
          issued_on == o.issued_on &&
          cancelled_on == o.cancelled_on &&
          rps_serial_number == o.rps_serial_number &&
          rps_number == o.rps_number &&
          city_service_code == o.city_service_code &&
          federal_service_code == o.federal_service_code &&
          description == o.description &&
          services_amount == o.services_amount &&
          deductions_amount == o.deductions_amount &&
          discount_unconditioned_amount == o.discount_unconditioned_amount &&
          discount_conditioned_amount == o.discount_conditioned_amount &&
          base_tax_amount == o.base_tax_amount &&
          iss_rate == o.iss_rate &&
          iss_tax_amount == o.iss_tax_amount &&
          ir_amount_withheld == o.ir_amount_withheld &&
          pis_amount_withheld == o.pis_amount_withheld &&
          cofins_amount_withheld == o.cofins_amount_withheld &&
          csll_amount_withheld == o.csll_amount_withheld &&
          inss_amount_withheld == o.inss_amount_withheld &&
          iss_amount_withheld == o.iss_amount_withheld &&
          others_amount_withheld == o.others_amount_withheld &&
          amount_withheld == o.amount_withheld &&
          amount_net == o.amount_net &&
          approximate_tax == o.approximate_tax &&
          created_on == o.created_on &&
          modified_on == o.modified_on
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, environment, flow_status, flow_message, provider, borrower, batch_number, batch_check_number, number, check_code, status, rps_type, rps_status, taxation_type, issued_on, cancelled_on, rps_serial_number, rps_number, city_service_code, federal_service_code, description, services_amount, deductions_amount, discount_unconditioned_amount, discount_conditioned_amount, base_tax_amount, iss_rate, iss_tax_amount, ir_amount_withheld, pis_amount_withheld, cofins_amount_withheld, csll_amount_withheld, inss_amount_withheld, iss_amount_withheld, others_amount_withheld, amount_withheld, amount_net, approximate_tax, created_on, modified_on].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = NfeClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
